### ISSUE TITLE
Windows issue at last step: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by MadPonyInteractive** [magic-quill/MagicQuill#35]
(MagicQuill) H:\magic-quil\MagicQuill>set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py
Traceback (most recent call last):
  File "H:\magic-quil\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "H:\magic-quil\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "H:\magic-quil\MagicQuill\MagicQuill\brushnet_nodes.py", line 11, in <module>
    import comfy.sd
  File "H:\magic-quil\MagicQuill\MagicQuill\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "H:\magic-quil\MagicQuill\MagicQuill\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "H:\magic-quil\MagicQuill\MagicQuill\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "H:\roop-unleashed\installer_files\conda\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "H:\roop-unleashed\installer_files\conda\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA ena

**Comment by mertkemal1131** [comment]
From the windows installation guide follow the steps from 14 to end

**Comment by NomadLuis** [comment]
updating pytorch worked for me

**Comment by zliucz** [comment]
Hi, you may try to re-install the pytorch by using the following command:

```
pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
```

This should work fine on Python 3.8 environment.

**Comment by MadPonyInteractive** [comment]
> Hi, you may try to re-install the pytorch by using the following command:
> 
> ```
> pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> This should work fine on Python 3.8 environment.

Thank you, it solved it.

**Comment by DroDellaro** [comment]
Hi, I tried to re-install pytorch but keep getting the error...

(MagicQuill) S:\MagicQuill>pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch==2.1.2 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (2.1.2)
Requirement already satisfied: torchvision==0.16.2 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (0.16.2)
Requirement already satisfied: filelock in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torch==2.1.2) (3.16.1)
Requirement already satisfied: typing-extensions in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torch==2.1.2) (4.12.2)
Requirement already satisfied: sympy in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torch==2.1.2) (1.13.3)
Requirement already satisfied: networkx in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torch==2.1.2) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torch==2.1.2) (3.1.4)
Requirement already satisfied: fsspec in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torch==2.1.2) (2024.10.0)
Requirement already satisfied: numpy in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torchvision==0.16.2) (1.26.4)
Requirement already satisfied: requests in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torchvision==0.16.2) (2.32.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from torchvision==0.16.2) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from jinja2->torch==2.1.2) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from requests->torchvision==0.16.2) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from requests->torchvision==0.16.2) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from requests->torchvision==0.16.2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from requests->torchvision==0.16.2) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dro\.conda\envs\magicquill\lib\site-packages (from sympy->torch==2.1.2) (1.3.0)

(MagicQuill) S:\MagicQuill>python gradio_run.py
Traceback (most recent call last):
  File "S:\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "S:\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "S:\MagicQuill\MagicQuill\brushnet_nodes.py", line 11, in <module>
    import comfy.sd
  File "S:\MagicQuill\MagicQuill\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "S:\MagicQuill\MagicQuill\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "S:\MagicQuill\MagicQuill\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Dro\.conda\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\Dro\.conda\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Amark-cheey** [comment]
(MagicQuill) hujh@a6002:~/expirement/1-imageedit/MagicQuill-tt$ **pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118**
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (2.1.2+cu118)
Requirement already satisfied: torchvision in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (0.16.2+cu118)
Requirement already satisfied: torchaudio in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (2.1.2+cu118)
Requirement already satisfied: filelock in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (4.11.0)
Requirement already satisfied: sympy in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (1.13.1)
Requirement already satisfied: networkx in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (2024.2.0)
Requirement already satisfied: triton==2.1.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (2.1.0)
Requirement already satisfied: numpy in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torchvision) (1.26.3)
Requirement already satisfied: requests in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torchvision) (2.28.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torchvision) (10.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
(MagicQuill) hujh@a6002:~/expirement/1-imageedit/MagicQuill-tt$ CUDA_VISIBLE_DEVICES="0" python gradio_run.py 
Traceback (most recent call last):
  File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/brushnet_nodes.py", line 11, in <module>
    import comfy.sd
  File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/comfy/model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/comfy/model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/torch/cuda/__init__.py", line 940, in current_device
    _lazy_init()
  File "/home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/torch/cuda/__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
**AssertionError: Torch not compiled with CUDA enabled**



I have followed the instructions to install it, but the situation is still the same.

**Comment by Amark-cheey** [comment]
(MagicQuill) hujh@a6002:/expirement/1-imageedit/MagicQuill-tt$ pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (2.1.2+cu118)
Requirement already satisfied: torchvision in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (0.16.2+cu118)
Requirement already satisfied: torchaudio in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (2.1.2+cu118)
Requirement already satisfied: filelock in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (4.11.0)
Requirement already satisfied: sympy in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (1.13.1)
Requirement already satisfied: networkx in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (2024.2.0)
Requirement already satisfied: triton==2.1.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torch) (2.1.0)
Requirement already satisfied: numpy in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torchvision) (1.26.3)
Requirement already satisfied: requests in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torchvision) (2.28.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from torchvision) (10.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
(MagicQuill) hujh@a6002:/expirement/1-imageedit/MagicQuill-tt$ CUDA_VISIBLE_DEVICES="0" python gradio_run.py
Traceback (most recent call last):
File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/gradio_run.py", line 17, in
from MagicQuill.scribble_color_edit import ScribbleColorEditModel
File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/scribble_color_edit.py", line 9, in
from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/brushnet_nodes.py", line 11, in
import comfy.sd
File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/comfy/sd.py", line 5, in
from comfy import model_management
File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/comfy/model_management.py", line 119, in
total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
File "/home/hujh/expirement/1-imageedit/MagicQuill-tt/MagicQuill/comfy/model_management.py", line 88, in get_torch_device
return torch.device(torch.cuda.current_device())
File "/home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/torch/cuda/init.py", line 940, in current_device
_lazy_init()
File "/home/hujh/miniconda3/envs/MagicQuill/lib/python3.10/site-packages/torch/cuda/init.py", line 310, in _lazy_init
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I have followed the instructions to install it, but the situation is still the same.
